[package]
name = "qbit-rs"
version = "0.4.7"
edition = "2021"
license = "MIT"
description = "A Rust library for interacting with qBittorrent's Web API"
readme = "README.md"
documentation = "https://docs.rs/qbit-rs"
repository = "https://github.com/George-Miao/qbit"
homepage = "https://github.com/George-Miao/qbit"
authors = ["George Miao <gm@miao.dev>"]
keywords = ["qbit", "qBittorrent", "web", "api", "torrent"]
categories = ["network-programming"]

[package.metadata.docs.rs]
features = ["docs"]
rustdoc-args = ["--cfg", "feature=\"docs\""]

[features]
default = ["builder", "default-tls"]
rustls = ["reqwest/rustls"]
default-tls = ["reqwest/default-tls"]
native-tls = ["reqwest/native-tls"]
docs = []

# enables typed-builder on args types
builder = ["dep:typed-builder"]

[dependencies]
typed-builder = { version = "0.23", optional = true }
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.13", default-features = false, features = [
  "charset",
  "form",
  "http2",
  "json",
  "multipart",
  "query",
] }
url = { version = "2", features = ["serde"] }

mod_use = "0.2"
serde-value = "0.7"
serde_repr = "0.1"
serde_with = "3"
tap = "1"
thiserror = "2"
tracing = "0.1.40"
serde_json = "1"
bytes = "1"
[dev-dependencies]
tokio = { version = "1", features = ["full"] }

dotenv = "0.15"
tracing-subscriber = "0.3"
